// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq1MzHR4oL2zrLYAwflCcNM10I5ap8Of4',
    appId: '1:553234384489:ios:15db15e513be25f1f4c4f8',
    messagingSenderId: '553234384489',
    projectId: 'neurosense-abcfe',
    storageBucket: 'neurosense-abcfe.firebasestorage.app',
    iosBundleId: 'com.example.neurosense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq1MzHR4oL2zrLYAwflCcNM10I5ap8Of4',
    appId: '1:553234384489:ios:15db15e513be25f1f4c4f8',
    messagingSenderId: '553234384489',
    projectId: 'neurosense-abcfe',
    storageBucket: 'neurosense-abcfe.firebasestorage.app',
    iosBundleId: 'com.example.neurosense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN7NPwwgzfaFU2ujII6TRzgl1_2QP17O4',
    appId: '1:553234384489:web:0561facd7c865c69f4c4f8',
    messagingSenderId: '553234384489',
    projectId: 'neurosense-abcfe',
    authDomain: 'neurosense-abcfe.firebaseapp.com',
    storageBucket: 'neurosense-abcfe.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN7NPwwgzfaFU2ujII6TRzgl1_2QP17O4',
    appId: '1:553234384489:web:0561facd7c865c69f4c4f8',
    messagingSenderId: '553234384489',
    projectId: 'neurosense-abcfe',
    authDomain: 'neurosense-abcfe.firebaseapp.com',
    storageBucket: 'neurosense-abcfe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrTO5pxgMdJNxz9URz7yy0JKj8X5C_14A',
    appId: '1:553234384489:android:c4636fbd49a06370f4c4f8',
    messagingSenderId: '553234384489',
    projectId: 'neurosense-abcfe',
    storageBucket: 'neurosense-abcfe.firebasestorage.app',
  );

}